// Canonical exam summary field schema for Encounter.
// Source: clinic-authored "Phiếu tổng hợp kết quả khám" (PHIEU_TONG_HOP_KET_QUA_KHAM_PKMMA_CHINH_SUA.docx, 2026-05-10).
//
// Use this as the source of truth for: the deferred Encounter form, the
// patient printout docx mapping, and any future EMR/REDCap export.
//
// Field-level conventions (from doc section 15):
//   - eyeSplit: true → store as <key>_od and <key>_os; eyeSplit: 'binocular' → single value
//   - type: 'string' | 'number' | 'date' | 'enum' | 'binary' | 'multiselect' | 'text' | 'composite'
//     • composite = clinic-specific shape (refraction Sph/Cyl x Axis, time HH:MM, etc.) stored as string
//   - format: human-readable hint for the form (e.g. "YYYY-MM-DD", "mm", "D", "Sph/Cyl x Axis")
//   - enum: { value, label } pairs for enum/multiselect/binary types
//   - units: optional unit suffix ("mmHg", "µm", "mm", "D", "%", "cpm", "arcsec", "Δ")
//
// `eyeSplit: true` fields produce two stored keys when persisted (e.g.
// axial_length_od + axial_length_os) but appear as a single row in the form
// with OD/OS columns. `'binocular'` means there is only one value (no OD/OS).

const BINARY = [{ value: 0, label: 'Không' }, { value: 1, label: 'Có' }]
const GRADE_04 = [0, 1, 2, 3, 4].map((n) => ({ value: n, label: String(n) }))

module.exports = [
  {
    code: 'admin',
    title: '1. Thông tin người bệnh & hành chính',
    fields: [
      { key: 'patient_id', label: 'Mã người bệnh', type: 'string' },
      { key: 'visit_id', label: 'Mã lượt khám', type: 'string' },
      { key: 'visit_date', label: 'Ngày khám', type: 'date', format: 'YYYY-MM-DD' },
      { key: 'visit_type', label: 'Loại lần khám', type: 'enum', enum: [
        { value: 1, label: 'Lần đầu' }, { value: 2, label: 'Tái khám' },
        { value: 3, label: 'Cấp cứu' }, { value: 4, label: 'Khác' },
      ] },
      { key: 'full_name', label: 'Họ và tên', type: 'string' },
      { key: 'dob', label: 'Ngày sinh', type: 'date', format: 'YYYY-MM-DD' },
      { key: 'age', label: 'Tuổi', type: 'number', format: 'integer, auto from dob' },
      { key: 'sex', label: 'Giới tính', type: 'enum', enum: [
        { value: 1, label: 'Nam' }, { value: 2, label: 'Nữ' }, { value: 3, label: 'Khác/không khai báo' },
      ] },
      { key: 'phone', label: 'Điện thoại', type: 'string' },
      { key: 'address', label: 'Địa chỉ', type: 'text' },
      { key: 'guardian_name', label: 'Người giám hộ', type: 'string' },
      { key: 'occupation_grade', label: 'Nghề nghiệp / lớp học', type: 'string' },
      { key: 'chief_complaint', label: 'Lý do đến khám', type: 'text' },
      { key: 'examiner', label: 'Người khám', type: 'string' },
      { key: 'data_entry_by', label: 'Người nhập liệu', type: 'string' },
    ],
  },
  {
    code: 'history',
    title: '2. Tiền sử, yếu tố nguy cơ & sức khỏe toàn thân',
    fields: [
      { key: 'systemic_disease', label: 'Bệnh toàn thân hiện có', type: 'binary', enum: BINARY },
      { key: 'systemic_disease_type', label: 'Loại bệnh toàn thân', type: 'multiselect',
        format: 'ĐTĐ, THA, hen, dị ứng, tự miễn, tuyến giáp, khác' },
      { key: 'allergy_history', label: 'Dị ứng thuốc/thức ăn', type: 'binary', enum: BINARY,
        format: 'ghi rõ tác nhân' },
      { key: 'current_medication', label: 'Thuốc đang dùng', type: 'text',
        format: 'tên thuốc, liều, tần suất' },
      { key: 'atopy_history', label: 'Cơ địa dị ứng/viêm da cơ địa', type: 'binary', enum: BINARY },
      { key: 'asthma_rhinitis', label: 'Hen/viêm mũi dị ứng', type: 'binary', enum: BINARY },
      { key: 'autoimmune_disease', label: 'Bệnh tự miễn', type: 'binary', enum: BINARY, format: 'ghi rõ' },
      { key: 'diabetes', label: 'Đái tháo đường', type: 'binary', enum: BINARY, format: 'ghi type nếu biết' },
      { key: 'hypertension', label: 'Tăng huyết áp', type: 'binary', enum: BINARY },
      { key: 'prematurity_low_bw', label: 'Sinh non/cân nặng sơ sinh thấp', type: 'binary', enum: BINARY,
        format: 'tuần thai/cân nặng nếu có' },
      { key: 'sleep_quality', label: 'Chất lượng giấc ngủ', type: 'enum',
        enum: [1, 2, 3, 4, 5].map((n) => ({ value: n, label: `${n} ${n === 1 ? '(Rất kém)' : n === 5 ? '(Rất tốt)' : ''}`.trim() })) },
      { key: 'near_work_hours', label: 'Thời gian nhìn gần/ngày', type: 'number', units: 'giờ/ngày' },
      { key: 'screen_time_hours', label: 'Thời gian màn hình/ngày', type: 'number', units: 'giờ/ngày' },
      { key: 'outdoor_time_hours', label: 'Thời gian ngoài trời/ngày', type: 'number', units: 'giờ/ngày' },
      { key: 'smoking_exposure', label: 'Tiếp xúc khói thuốc', type: 'binary', enum: BINARY },
      { key: 'ocular_history', label: 'Tiền sử bệnh mắt cá nhân', type: 'binary', enum: BINARY, format: 'ghi rõ bệnh' },
      { key: 'ocular_surgery_trauma', label: 'Phẫu thuật/chấn thương mắt', type: 'binary', enum: BINARY,
        format: 'ghi mắt, thời điểm, can thiệp' },
      { key: 'optical_history', label: 'Tiền sử đeo kính/contact lens', type: 'text',
        format: 'Kính gọng / Ortho-K / soft CL / RGP / khác; thời gian sử dụng' },
      { key: 'family_myopia', label: 'Gia đình cận thị', type: 'enum', enum: [
        { value: 0, label: 'Không' }, { value: 1, label: 'Bố' }, { value: 2, label: 'Mẹ' },
        { value: 3, label: 'Cả hai' }, { value: 4, label: 'Anh/chị/em' },
      ] },
      { key: 'parent_myopia_degree', label: 'Độ cận của bố/mẹ nếu biết', type: 'text', units: 'D',
        format: 'ghi riêng bố/mẹ' },
      { key: 'family_ocular_disease', label: 'Bệnh mắt di truyền/gia đình', type: 'multiselect',
        format: 'glaucoma, keratoconus, retinal disease, khác' },
    ],
  },
  {
    code: 'refraction',
    title: '3. Khúc xạ & thị lực',
    note: 'Thị lực: Snellen 20/x hoặc logMAR hoặc ĐNT-Xm. Khúc xạ: Sph/Cyl x Axis; trụ âm.',
    fields: [
      { key: 'va_ucdva', label: 'Thị lực không kính xa', eyeSplit: true, type: 'composite', format: 'Snellen / logMAR / ĐNT' },
      { key: 'va_ucnva', label: 'Thị lực không kính gần', eyeSplit: true, type: 'composite', format: 'N48..N6 hoặc logMAR gần' },
      { key: 'old_rx', label: 'Kính cũ: đơn kính', eyeSplit: true, type: 'composite', format: 'Sph/Cyl x Axis; Add nếu có' },
      { key: 'va_old_glasses', label: 'Thị lực với kính cũ', eyeSplit: true, type: 'composite', format: 'Snellen / logMAR / ĐNT' },
      { key: 'ar_pre', label: 'Auto-refraction trước liệt điều tiết', eyeSplit: true, type: 'composite', format: 'Sph/Cyl x Axis; bước 0.25D' },
      { key: 'ret_pre', label: 'Soi bóng trước liệt điều tiết', eyeSplit: true, type: 'composite' },
      { key: 'subj_pre', label: 'Khúc xạ chủ quan trước liệt điều tiết', eyeSplit: true, type: 'composite' },
      { key: 'va_ref_distance', label: 'Thị lực với khúc xạ xa', eyeSplit: true, type: 'composite' },
      { key: 'va_ref_near', label: 'Thị lực với khúc xạ gần', eyeSplit: true, type: 'composite' },
      { key: 'cycloplegia_agent', label: 'Thuốc liệt điều tiết đã dùng', eyeSplit: 'binocular', type: 'string',
        format: 'Tropicamide / Cyclopentolate / Atropine; ghi nồng độ' },
      { key: 'cycloplegia_time', label: 'Thời điểm đo sau nhỏ thuốc', eyeSplit: 'binocular', type: 'string', format: 'HH:MM sau lần nhỏ cuối' },
      { key: 'ar_post', label: 'Auto-refraction sau liệt điều tiết', eyeSplit: true, type: 'composite' },
      { key: 'ret_post', label: 'Soi bóng sau liệt điều tiết', eyeSplit: true, type: 'composite' },
      { key: 'cyclo_refraction', label: 'Khúc xạ sau liệt điều tiết', eyeSplit: true, type: 'composite' },
      { key: 'va_cyclo_ref', label: 'Thị lực với khúc xạ sau liệt điều tiết', eyeSplit: true, type: 'composite' },
      { key: 'final_rx', label: 'Đơn kính cuối cùng', eyeSplit: true, type: 'composite', format: 'Sph/Cyl x Axis; Add; loại kính' },
      { key: 'se', label: 'Cầu tương đương', eyeSplit: true, type: 'number', units: 'D', format: 'SE = Sph + Cyl/2' },
      { key: 'add_power', label: 'ADD', eyeSplit: true, type: 'number', units: 'D', format: 'bước 0.25D' },
      { key: 'pd', label: 'PD / khoảng cách đồng tử', eyeSplit: 'binocular', type: 'string', units: 'mm', format: 'xa/gần nếu có' },
      { key: 'refraction_note', label: 'Ghi chú khúc xạ', eyeSplit: 'binocular', type: 'text' },
    ],
  },
  {
    code: 'binocular',
    title: '4. Thị giác hai mắt, điều tiết & stereopsis',
    fields: [
      { key: 'ocular_alignment', label: 'Tư thế mắt quan sát', eyeSplit: 'binocular', type: 'string',
        format: 'Ortho / XT / XP / ET / EP / Hyper; ghi mắt nếu lệch đứng' },
      { key: 'cover_distance', label: 'Test che mắt xa', eyeSplit: 'binocular', type: 'string', format: 'Ortho / XT / XP / ET / EP; mức độ' },
      { key: 'cover_near', label: 'Test che mắt gần', eyeSplit: 'binocular', type: 'string' },
      { key: 'pct_distance', label: 'Prism cover test xa', eyeSplit: 'binocular', type: 'string', units: 'Δ', format: 'số + BI/BO/BU/BD' },
      { key: 'pct_near', label: 'Prism cover test gần', eyeSplit: 'binocular', type: 'string', units: 'Δ' },
      { key: 'howell', label: 'Howell card', eyeSplit: 'binocular', type: 'string', units: 'Δ', format: 'X Δ exo/eso' },
      { key: 'npc', label: 'Cận điểm quy tụ break/recovery', eyeSplit: 'binocular', type: 'string', units: 'cm', format: 'vd 5/7 cm' },
      { key: 'nfv', label: 'Dự trữ phân kỳ xa/gần', eyeSplit: 'binocular', type: 'string', format: 'BI blur/break/recovery vd 8/12/6' },
      { key: 'pfv', label: 'Dự trữ quy tụ xa/gần', eyeSplit: 'binocular', type: 'string', format: 'BO blur/break/recovery' },
      { key: 'aa', label: 'Biên độ điều tiết', eyeSplit: true, type: 'number', units: 'D' },
      { key: 'mem', label: 'MEM/Nott retinoscopy', eyeSplit: true, type: 'string', units: 'D', format: '+/- D' },
      { key: 'nra_pra', label: 'NRA/PRA', eyeSplit: 'binocular', type: 'string', format: 'NRA +X / PRA -Y' },
      { key: 'maf', label: 'Thuận năng điều tiết đơn mắt', eyeSplit: true, type: 'number', units: 'cpm' },
      { key: 'baf', label: 'Thuận năng điều tiết hai mắt', eyeSplit: 'binocular', type: 'number', units: 'cpm' },
      { key: 'ac_a', label: 'Tỷ số AC/A', eyeSplit: 'binocular', type: 'string', format: 'Calculated / Gradient; vd 4:1' },
      { key: 'stereoacuity', label: 'Stereopsis', eyeSplit: 'binocular', type: 'number', units: 'arcsec' },
      { key: 'color_vision', label: 'Sắc giác', eyeSplit: 'binocular', type: 'string', format: 'Ishihara / HRR; số đúng/tổng' },
    ],
  },
  {
    code: 'slitlamp',
    title: '5. Sinh hiển vi / sức khỏe mắt',
    note: "Có thể ghi 'BT' nếu bình thường; khi bất thường ghi mô tả + mức độ.",
    fields: [
      { key: 'slitlamp_done', label: 'Khám sinh hiển vi đã thực hiện', eyeSplit: 'binocular', type: 'binary', enum: BINARY },
      { key: 'lids', label: 'Mi mắt', eyeSplit: true, type: 'text', format: 'BT/sưng/đỏ/phù/lật/quặm/sa mi' },
      { key: 'lid_margin', label: 'Bờ mi', eyeSplit: true, type: 'text' },
      { key: 'lashes', label: 'Lông mi', eyeSplit: true, type: 'text' },
      { key: 'meibomian_gland', label: 'Tuyến Meibomian', eyeSplit: true, type: 'enum',
        enum: [0, 1, 2, 3].map((n) => ({ value: n, label: ['BT', 'nhẹ', 'vừa', 'nặng'][n] })) },
      { key: 'tear_film', label: 'Phim nước mắt', eyeSplit: true, type: 'text' },
      { key: 'bulbar_conjunctiva', label: 'Kết mạc nhãn cầu', eyeSplit: true, type: 'text' },
      { key: 'palpebral_conjunctiva', label: 'Kết mạc sụn mi', eyeSplit: true, type: 'text' },
      { key: 'papillae_grade', label: 'Nhú gai', eyeSplit: true, type: 'enum', enum: GRADE_04 },
      { key: 'follicles_grade', label: 'Hột', eyeSplit: true, type: 'enum', enum: GRADE_04 },
      { key: 'cornea_clarity', label: 'Giác mạc - độ trong', eyeSplit: true, type: 'text' },
      { key: 'corneal_staining', label: 'Nhuộm giác mạc', eyeSplit: true, type: 'string', format: 'Oxford/NEI hoặc 0-5; vị trí' },
      { key: 'corneal_nv', label: 'Tân mạch giác mạc', eyeSplit: true, type: 'binary', enum: BINARY, format: 'vị trí/độ sâu' },
      { key: 'anterior_chamber', label: 'Tiền phòng', eyeSplit: true, type: 'text', format: 'sâu/nông; cell/flare 0-4+' },
      { key: 'iris', label: 'Mống mắt', eyeSplit: true, type: 'text' },
      { key: 'pupil', label: 'Đồng tử', eyeSplit: true, type: 'text', format: 'tròn đều / RAPD / kích thước' },
      { key: 'lens', label: 'Thể thủy tinh', eyeSplit: true, type: 'text', format: 'trong / đục nhân/vỏ/bao sau; grade' },
      { key: 'slitlamp_impression', label: 'Nhận xét sinh hiển vi', eyeSplit: 'binocular', type: 'text' },
    ],
  },
  {
    code: 'dryeye',
    title: '6. Khô mắt & bề mặt nhãn cầu',
    fields: [
      { key: 'dry_eye_symptom', label: 'Triệu chứng khô mắt', eyeSplit: 'binocular', type: 'binary', enum: BINARY,
        format: 'cộm/xốn/đỏ/chảy nước/mờ dao động' },
      { key: 'osdi_score', label: 'OSDI', eyeSplit: 'binocular', type: 'number', format: '0-100' },
      { key: 'speed_score', label: 'SPEED', eyeSplit: 'binocular', type: 'number', format: '0-28' },
      { key: 'cldeq8_score', label: 'CLDEQ-8', eyeSplit: 'binocular', type: 'number', format: 'cho người đeo CL' },
      { key: 'nibut', label: 'NIBUT', eyeSplit: true, type: 'number', units: 'giây' },
      { key: 'tbut', label: 'TBUT fluorescein', eyeSplit: true, type: 'number', units: 'giây' },
      { key: 'schirmer', label: 'Schirmer', eyeSplit: true, type: 'string', units: 'mm/5 phút', format: 'có/không gây tê' },
      { key: 'tmh', label: 'Tear meniscus height', eyeSplit: true, type: 'string', units: 'mm' },
      { key: 'tear_osmolarity', label: 'Osmolarity', eyeSplit: true, type: 'number', units: 'mOsm/L' },
      { key: 'meibography_loss', label: 'Meibography mất tuyến', eyeSplit: true, type: 'string', format: '% hoặc grade 0-3' },
      { key: 'mgd_grade', label: 'MGD grade', eyeSplit: true, type: 'enum',
        enum: [0, 1, 2, 3].map((n) => ({ value: n, label: ['Không', 'nhẹ', 'vừa', 'nặng'][n] })) },
      { key: 'ocular_surface_dx', label: 'Chẩn đoán bề mặt nhãn cầu', eyeSplit: 'binocular', type: 'multiselect',
        format: 'Dry eye / MGD / viêm bờ mi / dị ứng / khác' },
      { key: 'dry_eye_plan', label: 'Kế hoạch điều trị khô mắt', eyeSplit: 'binocular', type: 'text' },
    ],
  },
  {
    code: 'iop',
    title: '7. Nhãn áp',
    fields: [
      { key: 'iop', label: 'Nhãn áp', eyeSplit: true, type: 'number', units: 'mmHg' },
      { key: 'iop_method', label: 'Phương pháp đo', eyeSplit: 'binocular', type: 'enum', enum: [
        { value: 'NCT', label: 'NCT' }, { value: 'Goldmann', label: 'Goldmann' },
        { value: 'iCare', label: 'iCare' }, { value: 'other', label: 'Khác' },
      ] },
      { key: 'iop_time', label: 'Thời điểm đo', eyeSplit: 'binocular', type: 'string', format: 'HH:MM; trước/sau giãn nếu liên quan' },
      { key: 'iop_note', label: 'Ghi chú nhãn áp', eyeSplit: 'binocular', type: 'text' },
    ],
  },
  {
    code: 'fundus',
    title: '8. Đáy mắt / fundus examination',
    fields: [
      { key: 'fundus_exam_done', label: 'Khám đáy mắt đã thực hiện', eyeSplit: 'binocular', type: 'binary', enum: BINARY },
      { key: 'dilation_done', label: 'Giãn đồng tử', eyeSplit: 'binocular', type: 'binary', enum: BINARY },
      { key: 'dilation_agent', label: 'Thuốc giãn đồng tử', eyeSplit: 'binocular', type: 'string',
        format: 'Tropicamide / Phenylephrine / Cyclopentolate; nồng độ' },
      { key: 'fundus_method', label: 'Phương pháp khám', eyeSplit: 'binocular', type: 'enum', enum: [
        { value: 'direct', label: 'Direct' }, { value: 'indirect', label: 'Indirect' },
        { value: '90D', label: '90D' }, { value: '78D', label: '78D' },
        { value: 'fundus_photo', label: 'Fundus photo' }, { value: 'optos', label: 'Optos' }, { value: 'oct', label: 'OCT' },
      ] },
      { key: 'disc_color', label: 'Màu gai thị', eyeSplit: true, type: 'text', format: 'BT/nhạt/phù/xung huyết' },
      { key: 'disc_margin', label: 'Bờ gai thị', eyeSplit: true, type: 'text', format: 'rõ/mờ; vị trí nếu mờ' },
      { key: 'cdr_vertical', label: 'Tỷ lệ C/D dọc', eyeSplit: true, type: 'number', format: '0.0-1.0' },
      { key: 'cdr_horizontal', label: 'Tỷ lệ C/D ngang', eyeSplit: true, type: 'number', format: '0.0-1.0' },
      { key: 'disc_tilt_ppa', label: 'Gai nghiêng / PPA', eyeSplit: true, type: 'binary', enum: BINARY, format: 'tilt, PPA α/β' },
      { key: 'macula_status', label: 'Hoàng điểm', eyeSplit: true, type: 'text',
        format: 'BT / mất ánh fovea / phù / xuất tiết / sẹo / teo' },
      { key: 'foveal_reflex', label: 'Phản xạ hố trung tâm', eyeSplit: true, type: 'enum',
        enum: [0, 1, 2].map((n) => ({ value: n, label: ['Không', 'Có', 'Không đánh giá'][n] })) },
      { key: 'myopic_maculopathy', label: 'Myopic maculopathy', eyeSplit: true, type: 'enum',
        enum: [0, 1, 2, 3, 4].map((n) => ({
          value: n,
          label: ['None', 'Tessellated', 'Diffuse atrophy', 'Patchy atrophy', 'Macular atrophy'][n],
        })) },
      { key: 'vessel_status', label: 'Mạch máu võng mạc', eyeSplit: true, type: 'text', format: 'A/V nếu có' },
      { key: 'peripheral_retina', label: 'Võng mạc chu biên', eyeSplit: true, type: 'text', format: 'vị trí giờ' },
      { key: 'lattice_degeneration', label: 'Lattice degeneration', eyeSplit: true, type: 'binary', enum: BINARY },
      { key: 'retinal_hole_tear', label: 'Lỗ/rách võng mạc', eyeSplit: true, type: 'binary', enum: BINARY },
      { key: 'retinal_detachment', label: 'Bong võng mạc', eyeSplit: true, type: 'binary', enum: BINARY },
      { key: 'pathologic_myopia_signs', label: 'Dấu hiệu cận thị bệnh lý', eyeSplit: true, type: 'binary', enum: BINARY,
        format: 'Staphyloma / lacquer crack / CNV / Fuchs spot' },
      { key: 'fundus_impression', label: 'Nhận xét đáy mắt', eyeSplit: 'binocular', type: 'text' },
      { key: 'referral_needed', label: 'Cần chuyển tuyến', eyeSplit: 'binocular', type: 'binary', enum: BINARY,
        format: 'lý do và mức khẩn' },
    ],
  },
  {
    code: 'topography',
    title: '9. Bản đồ giác mạc / corneal topography',
    fields: [
      { key: 'k1', label: 'K1', eyeSplit: true, type: 'number', units: 'D' },
      { key: 'k2', label: 'K2', eyeSplit: true, type: 'number', units: 'D' },
      { key: 'k_axis', label: 'Trục K phẳng/K dốc', eyeSplit: true, type: 'number', format: '1-180°' },
      { key: 'corneal_astigmatism', label: 'Loạn thị giác mạc', eyeSplit: true, type: 'number', units: 'D', format: 'K2-K1' },
      { key: 'km', label: 'Km / K trung bình', eyeSplit: true, type: 'number', units: 'D' },
      { key: 'eccentricity', label: 'Eccentricity e', eyeSplit: true, type: 'number', format: '0.00-1.00' },
      { key: 'q_value', label: 'Q value', eyeSplit: true, type: 'number' },
      { key: 'kmax', label: 'Kmax', eyeSplit: true, type: 'number', units: 'D' },
      { key: 'cct_topo', label: 'Độ dày giác mạc trung tâm', eyeSplit: true, type: 'number', units: 'µm' },
      { key: 'topo_morphology', label: 'Nhận xét hình thái', eyeSplit: true, type: 'text' },
      { key: 'cone_location', label: 'Vị trí đỉnh chóp/nghi ngờ', eyeSplit: true, type: 'string',
        format: 'trung tâm / dưới / thái dương / mũi' },
      { key: 'topo_file_link', label: 'Link file bản đồ', eyeSplit: 'binocular', type: 'string', format: 'URL hoặc đường dẫn' },
      { key: 'topo_note', label: 'Ghi chú bản đồ', eyeSplit: 'binocular', type: 'text' },
    ],
  },
  {
    code: 'biometry',
    title: '10. Sinh trắc học nhãn cầu / ocular biometry',
    fields: [
      { key: 'axial_length', label: 'Trục nhãn cầu AL', eyeSplit: true, type: 'number', units: 'mm', format: '17-35 mm' },
      { key: 'corneal_radius', label: 'Bán kính giác mạc CR', eyeSplit: true, type: 'number', units: 'mm' },
      { key: 'al_cr_ratio', label: 'Tỷ số AL/CR', eyeSplit: true, type: 'number' },
      { key: 'acd', label: 'Độ sâu tiền phòng ACD', eyeSplit: true, type: 'number', units: 'mm' },
      { key: 'lens_thickness', label: 'Độ dày thể thủy tinh LT', eyeSplit: true, type: 'number', units: 'mm' },
      { key: 'wtw', label: 'White-to-white WTW', eyeSplit: true, type: 'number', units: 'mm' },
      { key: 'cct_biometry', label: 'CCT từ sinh trắc', eyeSplit: true, type: 'number', units: 'µm' },
      { key: 'axial_length_change', label: 'Thay đổi AL so với lần trước', eyeSplit: true, type: 'number', units: 'mm' },
      { key: 'biometry_file_link', label: 'Link file sinh trắc', eyeSplit: 'binocular', type: 'string' },
      { key: 'biometry_impression', label: 'Nhận xét sinh trắc', eyeSplit: 'binocular', type: 'text' },
    ],
  },
  {
    code: 'oct',
    title: '11. OCT & hình ảnh lâm sàng',
    fields: [
      { key: 'oct_done', label: 'OCT đã thực hiện', eyeSplit: 'binocular', type: 'binary', enum: BINARY },
      { key: 'oct_macula', label: 'OCT hoàng điểm', eyeSplit: true, type: 'text' },
      { key: 'central_macular_thickness', label: 'Độ dày hoàng điểm trung tâm', eyeSplit: true, type: 'number', units: 'µm' },
      { key: 'rnfl_avg', label: 'OCT RNFL trung bình', eyeSplit: true, type: 'number', units: 'µm' },
      { key: 'gcc_gcip', label: 'GCC / GCIPL', eyeSplit: true, type: 'string', units: 'µm' },
      { key: 'oct_disc', label: 'OCT gai thị', eyeSplit: true, type: 'text' },
      { key: 'fundus_photo_taken', label: 'Ảnh đáy mắt', eyeSplit: 'binocular', type: 'binary', enum: BINARY },
      { key: 'image_quality', label: 'Chất lượng ảnh', eyeSplit: 'binocular', type: 'enum',
        enum: [1, 2, 3].map((n) => ({ value: n, label: ['Kém', 'Trung bình', 'Tốt'][n - 1] })) },
      { key: 'imaging_file_link', label: 'Link file hình ảnh', eyeSplit: 'binocular', type: 'string' },
      { key: 'imaging_impression', label: 'Nhận xét OCT/hình ảnh', eyeSplit: 'binocular', type: 'text' },
    ],
  },
  {
    code: 'contactlens',
    title: '12. Contact lens & quản lý cận thị',
    fields: [
      { key: 'myopia_management_candidate', label: 'Đối tượng quản lý cận thị', type: 'binary', enum: BINARY,
        format: 'dựa vào tuổi, SE, AL, tốc độ tiến triển, gia đình' },
      { key: 'myopia_management_type', label: 'Phương pháp quản lý cận thị', type: 'multiselect', enum: [
        { value: 1, label: 'Kính thường' }, { value: 2, label: 'DIMS' }, { value: 3, label: 'HAL' },
        { value: 4, label: 'Ortho-K' }, { value: 5, label: 'Soft CL kiểm soát cận' },
        { value: 6, label: 'Atropine' }, { value: 7, label: 'Phối hợp' },
      ] },
      { key: 'atropine_concentration', label: 'Nồng độ atropine', type: 'enum', enum: [
        { value: '0.01', label: '0.01%' }, { value: '0.025', label: '0.025%' },
        { value: '0.05', label: '0.05%' }, { value: 'other', label: 'Khác' },
      ], format: 'số lần/ngày, tác dụng phụ' },
      { key: 'spectacle_type', label: 'Loại kính gọng', type: 'string',
        format: 'thường / Stellest / DIMS / HAL / Bifocal / Progressive / khác' },
      { key: 'contact_lens_type', label: 'Loại contact lens', type: 'string',
        format: 'Soft CL / Ortho-K / RGP / Scleral / khác; brand, BC, Dia, Power' },
      { key: 'cl_rx', label: 'Độ lens thử/đơn CL OD/OS', type: 'text' },
      { key: 'cl_fit_assessment', label: 'Đánh giá fit contact lens', type: 'text',
        format: 'centration, movement, coverage, fluorescein, comfort' },
      { key: 'compliance', label: 'Tuân thủ điều trị', type: 'enum',
        enum: [1, 2, 3].map((n) => ({ value: n, label: ['Kém', 'Trung bình', 'Tốt'][n - 1] })),
        format: 'số giờ/ngày, số ngày/tuần' },
      { key: 'adverse_event', label: 'Biến cố / tác dụng phụ', type: 'binary', enum: BINARY,
        format: 'đỏ / cộm / viêm / halos / dị ứng / nhạy sáng' },
      { key: 'counselling_given', label: 'Tư vấn đã thực hiện', type: 'multiselect',
        format: 'ngoài trời, nhìn gần, ánh sáng, vệ sinh lens, dấu hiệu nguy hiểm' },
    ],
  },
  {
    code: 'plan',
    title: '13. Chẩn đoán, xử trí & hẹn tái khám',
    fields: [
      { key: 'primary_diagnosis', label: 'Chẩn đoán chính', type: 'text', format: 'có thể kèm ICD-10' },
      { key: 'secondary_diagnosis', label: 'Chẩn đoán phụ', type: 'text' },
      { key: 'icd10_code', label: 'Mã ICD-10', type: 'string', format: 'vd H52.1, H52.2, H04.1' },
      { key: 'clinical_summary', label: 'Kết luận ngắn gọn', type: 'text' },
      { key: 'final_prescription_summary', label: 'Đơn kính/CL cuối cùng', type: 'text', format: 'OD/OS, Add, PD, loại' },
      { key: 'medication_plan', label: 'Thuốc / điều trị', type: 'text', format: 'tên, liều, tần suất, thời gian' },
      { key: 'advice_given', label: 'Tư vấn', type: 'text' },
      { key: 'referral_status', label: 'Cần chuyển chuyên khoa / cấp cứu', type: 'enum',
        enum: [0, 1, 2].map((n) => ({ value: n, label: ['Không', 'Thường quy', 'Khẩn'][n] })),
        format: 'ghi lý do' },
      { key: 'next_visit_date', label: 'Ngày hẹn tái khám', type: 'date', format: 'YYYY-MM-DD' },
      { key: 'followup_interval', label: 'Khoảng cách tái khám', type: 'string', format: 'vd 3 tháng' },
      { key: 'responsible_clinician', label: 'Chữ ký / người chịu trách nhiệm', type: 'string' },
    ],
  },
  {
    code: 'followup',
    title: '14. Theo dõi tái khám / longitudinal follow-up',
    fields: [
      { key: 'followup_visit_no', label: 'Số thứ tự lần khám', eyeSplit: 'binocular', type: 'number' },
      { key: 'followup_date', label: 'Ngày tái khám', eyeSplit: 'binocular', type: 'date', format: 'YYYY-MM-DD' },
      { key: 'symptom_change', label: 'Triệu chứng thay đổi', eyeSplit: 'binocular', type: 'enum', enum: [
        { value: 'better', label: 'Tốt hơn' }, { value: 'same', label: 'Không đổi' }, { value: 'worse', label: 'Xấu hơn' },
      ], format: 'chi tiết' },
      { key: 'va_change', label: 'Thay đổi thị lực', eyeSplit: true, type: 'string' },
      { key: 'se_change', label: 'Thay đổi SE', eyeSplit: true, type: 'number', units: 'D' },
      { key: 'al_change', label: 'Thay đổi AL', eyeSplit: true, type: 'number', units: 'mm' },
      { key: 'followup_compliance', label: 'Tuân thủ điều trị', eyeSplit: 'binocular', type: 'enum',
        enum: [1, 2, 3].map((n) => ({ value: n, label: ['Kém', 'Trung bình', 'Tốt'][n - 1] })) },
      { key: 'followup_adverse_event', label: 'Biến cố / tác dụng phụ', eyeSplit: 'binocular', type: 'binary', enum: BINARY },
      { key: 'treatment_change', label: 'Có đổi điều trị', eyeSplit: 'binocular', type: 'binary', enum: BINARY },
      { key: 'followup_plan', label: 'Kế hoạch tiếp theo', eyeSplit: 'binocular', type: 'text' },
    ],
  },
]
