// Sample output field definitions per service.
// Placeholder schemas — refine after walking through real exam paperwork
// with each station's KTV/BS. Used by the Khám page to render input forms.

const EYE_FIELDS = (prefix) => ([
  { key: `${prefix}_sphere`, label: `${prefix.toUpperCase()} Sphere`, type: 'number', step: 0.25 },
  { key: `${prefix}_cyl`,    label: `${prefix.toUpperCase()} Cyl`,    type: 'number', step: 0.25 },
  { key: `${prefix}_axis`,   label: `${prefix.toUpperCase()} Axis`,   type: 'number', step: 1 },
])

const SERVICE_OUTPUT_FIELDS = {
  'SVC-AUTOREF': [
    ...EYE_FIELDS('od'),
    ...EYE_FIELDS('os'),
    { key: 'od_k1', label: 'OD K1', type: 'number', step: 0.01 },
    { key: 'od_k2', label: 'OD K2', type: 'number', step: 0.01 },
    { key: 'os_k1', label: 'OS K1', type: 'number', step: 0.01 },
    { key: 'os_k2', label: 'OS K2', type: 'number', step: 0.01 },
    { key: 'old_glasses', label: 'Số kính cũ (nếu BN mang)', type: 'text' },
    { key: 'note', label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-REFRACT': [
    { key: 'od_va_uncorrected', label: 'OD UCVA', type: 'text', placeholder: '20/20, 6/6, 0.8' },
    { key: 'os_va_uncorrected', label: 'OS UCVA', type: 'text' },
    { key: 'od_va_corrected',   label: 'OD BCVA', type: 'text' },
    { key: 'os_va_corrected',   label: 'OS BCVA', type: 'text' },
    ...EYE_FIELDS('od'),
    ...EYE_FIELDS('os'),
    { key: 'od_add', label: 'OD Add (presbyopia)', type: 'number', step: 0.25 },
    { key: 'os_add', label: 'OS Add', type: 'number', step: 0.25 },
    { key: 'pd', label: 'PD (mm)', type: 'number', step: 0.5 },
    { key: 'retinoscopy_dry', label: 'SBĐT — dry retinoscopy', type: 'textarea' },
    { key: 'note', label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-TG2M': [
    { key: 'cover_test',       label: 'Cover test', type: 'textarea' },
    { key: 'worth_4dot',       label: 'Worth 4-dot', type: 'text' },
    { key: 'stereopsis',       label: 'Lập thể (sec arc)', type: 'number' },
    { key: 'fusional_reserve', label: 'Fusional reserves', type: 'textarea' },
    { key: 'accommodation',    label: 'Biên độ điều tiết (D)', type: 'number', step: 0.25 },
    { key: 'note',             label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-CYCLO': [
    { key: 'drug',         label: 'Thuốc', type: 'select', options: ['Cyclopentolate 1%', 'Tropicamide 1%', 'Atropine 1%'] },
    { key: 'drops_at',     label: 'Thời điểm nhỏ', type: 'datetime' },
    { key: 'remeasure_at', label: 'Thời điểm đo lại', type: 'datetime' },
    ...EYE_FIELDS('od_wet'),
    ...EYE_FIELDS('os_wet'),
    { key: 'retinoscopy_wet', label: 'SBĐT — wet retinoscopy', type: 'textarea' },
    { key: 'note', label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-CONTRAST': [
    { key: 'od_score', label: 'OD score', type: 'number' },
    { key: 'os_score', label: 'OS score', type: 'number' },
    { key: 'note', label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-ISHIHARA': [
    { key: 'result', label: 'Kết quả', type: 'select', options: ['Bình thường', 'Mù màu đỏ-xanh', 'Mù màu khác', 'Khác'] },
    { key: 'plates_correct', label: 'Số plate đúng / tổng', type: 'text' },
    { key: 'note', label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-IOP': [
    { key: 'od_icare',    label: 'OD iCare (mmHg)', type: 'number', step: 0.1 },
    { key: 'os_icare',    label: 'OS iCare (mmHg)', type: 'number', step: 0.1 },
    { key: 'od_goldmann', label: 'OD Goldmann (mmHg, nếu confirm)', type: 'number', step: 0.1 },
    { key: 'os_goldmann', label: 'OS Goldmann (mmHg, nếu confirm)', type: 'number', step: 0.1 },
    { key: 'note',        label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-SLIT': [
    { key: 'event_kind', label: 'Loại event', type: 'select', options: [
      { value: 'initial',    label: 'Initial — chỉ định tests' },
      { value: 'conclusion', label: 'Conclusion — kết luận + kê đơn' },
      { value: 'cl_eval',    label: 'CL evaluation (ortho-K) — đánh giá kính' },
    ] },
    { key: 'od_findings', label: 'OD findings (cornea / AC / iris / lens)', type: 'textarea' },
    { key: 'os_findings', label: 'OS findings', type: 'textarea' },
    { key: 'tbut_od',     label: 'OD TBUT (sec)', type: 'number' },
    { key: 'tbut_os',     label: 'OS TBUT (sec)', type: 'number' },
    { key: 'fluorescein_findings', label: 'Fluorescein staining', type: 'textarea' },
    { key: 'fundus_handheld', label: 'Soi đáy mắt 90D/78D', type: 'textarea' },
    { key: 'impression',  label: 'Ấn tượng / chẩn đoán', type: 'textarea' },
    { key: 'plan',        label: 'Plan / chỉ định', type: 'textarea' },
    { key: 'rx_glasses',  label: 'Đơn kính (nếu kê)', type: 'textarea' },
    { key: 'rx_meds',     label: 'Đơn thuốc (nếu kê)', type: 'textarea' },
    { key: 'rx_tpcn',     label: 'Đơn TPCN (nếu kê)', type: 'textarea' },
    { key: 'rx_baitap',   label: 'Đơn bài tập (nếu kê)', type: 'textarea' },
  ],
  'SVC-BIO': [
    { key: 'od_findings', label: 'OD đáy mắt', type: 'textarea' },
    { key: 'os_findings', label: 'OS đáy mắt', type: 'textarea' },
    { key: 'note', label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-SCHIRMER': [
    { key: 'od_mm',  label: 'OD (mm sau 5 phút)', type: 'number' },
    { key: 'os_mm',  label: 'OS (mm sau 5 phút)', type: 'number' },
    { key: 'with_anesthesia', label: 'Có gây tê?', type: 'boolean' },
    { key: 'note',   label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-TOPO': [
    { key: 'od_k1', label: 'OD K1', type: 'number', step: 0.01 },
    { key: 'od_k2', label: 'OD K2', type: 'number', step: 0.01 },
    { key: 'os_k1', label: 'OS K1', type: 'number', step: 0.01 },
    { key: 'os_k2', label: 'OS K2', type: 'number', step: 0.01 },
    { key: 'od_eccentricity', label: 'OD eccentricity', type: 'number', step: 0.01 },
    { key: 'os_eccentricity', label: 'OS eccentricity', type: 'number', step: 0.01 },
    { key: 'shape_pattern', label: 'Dạng giác mạc', type: 'select', options: ['Bình thường', 'Keratoconus suspect', 'Keratoconus', 'Pellucid', 'Khác'] },
    { key: 'image_url', label: 'Link ảnh (placeholder)', type: 'text' },
    { key: 'note', label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-OCT-ANT': [
    { key: 'od_pachymetry', label: 'OD độ dày giác mạc (μm)', type: 'number' },
    { key: 'os_pachymetry', label: 'OS độ dày giác mạc (μm)', type: 'number' },
    { key: 'od_acd',        label: 'OD ACD (mm)', type: 'number', step: 0.01 },
    { key: 'os_acd',        label: 'OS ACD (mm)', type: 'number', step: 0.01 },
    { key: 'image_url',     label: 'Link ảnh', type: 'text' },
    { key: 'note',          label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-OCT-POST': [
    { key: 'od_rnfl_avg', label: 'OD RNFL average (μm)', type: 'number' },
    { key: 'os_rnfl_avg', label: 'OS RNFL average (μm)', type: 'number' },
    { key: 'od_macula_thickness', label: 'OD macular thickness (μm)', type: 'number' },
    { key: 'os_macula_thickness', label: 'OS macular thickness (μm)', type: 'number' },
    { key: 'image_url',     label: 'Link ảnh', type: 'text' },
    { key: 'note',          label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-FUNDUS': [
    { key: 'device', label: 'Thiết bị', type: 'select', options: ['DRS Plus', 'Vietcan'] },
    { key: 'od_findings', label: 'OD đáy mắt (mô tả)', type: 'textarea' },
    { key: 'os_findings', label: 'OS đáy mắt (mô tả)', type: 'textarea' },
    { key: 'image_url', label: 'Link ảnh', type: 'text' },
    { key: 'note', label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-DRYEYE': [
    { key: 'device', label: 'Thiết bị', type: 'select', options: ['IDRA', 'Medmont Meridia'] },
    { key: 'tbut_od', label: 'OD TBUT (sec)', type: 'number' },
    { key: 'tbut_os', label: 'OS TBUT (sec)', type: 'number' },
    { key: 'meibo_grade_od', label: 'OD Meibography grade', type: 'select', options: ['0', '1', '2', '3'] },
    { key: 'meibo_grade_os', label: 'OS Meibography grade', type: 'select', options: ['0', '1', '2', '3'] },
    { key: 'tear_meniscus', label: 'Tear meniscus', type: 'textarea' },
    { key: 'note', label: 'Ghi chú', type: 'textarea' },
  ],
  'SVC-BIOMETRY': [
    { key: 'device', label: 'Thiết bị', type: 'select', options: ['MediWorks AB800', 'Syseye', 'Optopol Revo (OCT trục)'] },
    { key: 'od_axial_length', label: 'OD Axial length (mm)', type: 'number', step: 0.01 },
    { key: 'os_axial_length', label: 'OS Axial length (mm)', type: 'number', step: 0.01 },
    { key: 'od_acd', label: 'OD ACD (mm)', type: 'number', step: 0.01 },
    { key: 'os_acd', label: 'OS ACD (mm)', type: 'number', step: 0.01 },
    { key: 'od_k', label: 'OD K (avg)', type: 'number', step: 0.01 },
    { key: 'os_k', label: 'OS K (avg)', type: 'number', step: 0.01 },
    { key: 'od_white_to_white', label: 'OD WTW (mm)', type: 'number', step: 0.1 },
    { key: 'os_white_to_white', label: 'OS WTW (mm)', type: 'number', step: 0.1 },
    { key: 'iol_calc_note', label: 'IOL calc / formula', type: 'textarea' },
  ],
  'SVC-CL-FIT': [
    { key: 'lens_type', label: 'Loại CL', type: 'select', options: ['Soft daily', 'Soft biweekly', 'Soft monthly', 'RGP', 'Ortho-K'] },
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'od_bc',    label: 'OD BC (mm)', type: 'number', step: 0.1 },
    { key: 'od_dia',   label: 'OD DIA (mm)', type: 'number', step: 0.1 },
    { key: 'od_power', label: 'OD Power', type: 'number', step: 0.25 },
    { key: 'os_bc',    label: 'OS BC (mm)', type: 'number', step: 0.1 },
    { key: 'os_dia',   label: 'OS DIA (mm)', type: 'number', step: 0.1 },
    { key: 'os_power', label: 'OS Power', type: 'number', step: 0.25 },
    { key: 'fit_assessment', label: 'Fit assessment', type: 'textarea' },
    { key: 'comfort', label: 'Comfort', type: 'select', options: ['Tốt', 'Khá', 'Kém'] },
    { key: 'va_with_trial', label: 'VA với trial lens (OD/OS)', type: 'text' },
    { key: 'final_rx', label: 'Đơn cuối (BC/DIA/Power per eye + brand)', type: 'textarea' },
  ],
  'SVC-MYOPIA-CONSULT': [
    { key: 'method',    label: 'Phương pháp', type: 'select', options: ['Ortho-K', 'Atropine 0.01-0.05%', 'Multifocal soft CL', 'Multifocal glasses', 'Khác'] },
    { key: 'parents_present', label: 'Phụ huynh có mặt?', type: 'boolean' },
    { key: 'discussion', label: 'Nội dung tư vấn', type: 'textarea' },
    { key: 'agreed_plan', label: 'Plan đã thống nhất', type: 'textarea' },
  ],
  'SVC-FB-REMOVE': [
    { key: 'eye',          label: 'Mắt', type: 'select', options: ['OD', 'OS', 'OU'] },
    { key: 'fb_location',  label: 'Vị trí dị vật', type: 'select', options: ['Kết mạc nhãn cầu', 'Kết mạc mi', 'Giác mạc', 'Khác'] },
    { key: 'fb_type',      label: 'Loại dị vật', type: 'text' },
    { key: 'method',       label: 'Phương pháp', type: 'select', options: ['Bông tăm', 'Kim tiêm vô trùng', 'Burr', 'Khác'] },
    { key: 'after_findings', label: 'Findings sau lấy', type: 'textarea' },
    { key: 'rx_meds',      label: 'Thuốc kê sau thủ thuật', type: 'textarea' },
  ],
}

module.exports = SERVICE_OUTPUT_FIELDS
